---
- name: Create / Update PanOS Security Rule
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    _commit: "{{ panos_commit | default(false) | bool }}"

  tasks:
    - name: Log ServiceNow ticket
      register: r_snow_ticket
      when: snow_sys_id is defined
      servicenow.itsm.api_info:
        resource: sc_req_item
        sys_id: "{{ snow_sys_id }}"

    - name: Define PanOS security rule
      register: r_panos_security_rule
      check_mode: "{{ not _commit }}"
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ panos_provider }}"
        rule_name: "{{ panos_rule_name }}"
        rule_type: "{{ panos_rule_type | default(omit) }}"
        action: "{{ panos_action | default('') | ternary(panos_action, 'allow') }}"
        location: "{{ panos_location | default('') | ternary(panos_location, omit) }}"
        source_zone: "{{ panos_source_zone | default('') | ternary ([panos_source_zone], ['any']) }}"
        source_ip: "{{ panos_source_ip | default('') | ternary ([panos_source_ip], ['any']) }}"
        destination_zone: "{{ panos_destination_zone | default('') | ternary ([panos_destination_zone], ['any']) }}"
        destination_ip: "{{ panos_destination_ip | default('') | ternary ([panos_destination_ip], ['any']) }}"
        state: "{{ panos_state | default('') | ternary (panos_state, 'present') }}"

    - name: Commit firewall changes
      when: _commit
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ panos_provider }}"
        description: "Changes committed by ansible on {{ lookup('pipe', 'date') }} based on request: {{ snow_ritm | default('N/A') }}"
