---
- name: Start a webserver
  hosts: role_webserver
  gather_facts: false
  become: true

  vars:
    network_connections:
      - name: System eth0
        type: ethernet
        interface_name: eth0
        ip:
          address:
            - 10.0.2.40/24
          gateway4: 10.0.2.20
          dns:
            - 10.0.2.1
    network_state:
      - name: System eth0
        type: ethernet
        state: up

  tasks:
    - name: Install required packages
      ansible.builtin.dnf:
        name: 
          - httpd
          - nmstate
          - NetworkManager
        state: present

    - name: Apply network configuration
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.network

    - name: Start httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
