---
- name: Start a webserver
  hosts: role_webserver
  gather_facts: false
  become: true

  vars:
    network_connections:
      - name: System eth0
        type: ethernet
        interface_name: eth0
        ip:
          address:
            - 10.0.2.40/24
          gateway4: 10.0.2.20
          route:
            - network: 169.254.169.254
    # network_state:
    #   - name: System eth0
    #     type: ethernet
    #     state: up
    #     ipv4:
    #       address:
    #       - ip: 10.0.2.40
    #         prefix-length: 24
    #       enabled: true

  tasks:
    - name: Apply network configuration
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.network

    - name: Install the latest version of Apache
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
