---
- name: Find interfaces with restricted ACL
  hosts: "{{ _hosts | default(omit) }}"
  gather_facts: no

  tasks:
    - name: Run show interfaces command
      cisco.ios.ios_command:
        commands:
          - show interfaces
      register: show_interfaces_output

    - name: Extract interface names with restricted ACL
      ansible.builtin.set_fact:
        restricted_interfaces: "{{ show_interfaces_output.stdout[0] | regex_findall('^(?!\\s*Interface)(\\S+).*access-group\\s+(\\S+)\\s+in\\s*$') }}"
      when: show_interfaces_output.stdout_lines[0] is match('.*access-group\\s+\\S+\\s+in.*')

    - name: Display restricted interfaces
      ansible.builtin.debug:
        var: restricted_interfaces