---
- afi: ipv4
  acls:
  - name: IPv4-ACL
    aces:
    - sequence: 10
      grant: deny
      source:
        any: true
      destination:
        address: 198.51.100.0
        wildcard_bits: 0.0.0.255
      protocol: tcp
    - sequence: 20
      grant: permit
      source:
        any: true
      destination:
        any: true
      protocol: tcp