---
- afi: ipv4
  prefix_lists:
    - name: IPv4-Prefix-List
      # description: IPv4 Prefix List # iosxr
      entries:
        - action: deny
          prefix: 1.0.0.0/8
          le: 15
          sequence: 5
        - action: deny
          prefix: 35.0.0.0/8
          ge: 10
          sequence: 10
        - action: deny
          prefix: 12.0.0.0/8
          ge: 15
          sequence: 15
        - action: deny
          prefix: 14.0.0.0/8
          ge: 20
          le: 21
          sequence: 20
- afi: ipv6
  prefix_lists:
    - name: IPv6-Prefix-List
      # description: IPv6 Prefix List # iosxr
      entries:
        - action: deny
          prefix: 2001:DB8:0:4::/64
          ge: 80
          le: 100
          sequence: 20