---
nxos_bgp_global_config:
  as_number: 65563
  router_id: 192.168.1.1
  bestpath:
    as_path:
      multipath_relax: True
    compare_neighborid: True
    cost_community_ignore: True
  confederation:
    identifier: 42
    peers:
      - 65020
      - 65030
      - 65040
  log_neighbor_changes: True
  maxas_limit: 20
  neighbors:
    - neighbor_address: 192.168.1.100
      neighbor_affinity_group:
        group_id: 160
      bmp_activate_server: 1
      remote_as: 65563
      description: NBR-1
      low_memory:
        exempt: True
    - neighbor_address: 192.168.1.101
      remote_as: 65563
      password:
        encryption: 7
        key: 12090404011C03162E
  neighbor_down:
    fib_accelerate: True
  vrfs:
    - vrf: site-1
      allocate_index: 5000
      local_as: 200
      log_neighbor_changes: True
      neighbors:
        - neighbor_address: 198.51.100.1
          description: site-1-nbr-1
          password:
            encryption: 3
            key: 13D4D3549493D2877B1DC116EE27A6BE
          remote_as: 65562
        - neighbor_address: 198.51.100.2
          remote_as: 65562
          description: site-1-nbr-2
    - vrf: site-2
      local_as: 300
      log_neighbor_changes: True
      neighbors:
        - neighbor_address: 203.0.113.2
          description: site-1-nbr-1
          password:
            encryption: 3
            key: AF92F4C16A0A0EC5BDF56CF58BC030F6
          remote_as: 65568
      neighbor_down:
        fib_accelerate: True