---
- name: Custom slack notification for networking vlan changes
  hosts: localhost

  tasks:
    - name: Check for stats
      block:
        - name: Assert expected stats exist
          ansible.builtin.assert:
            that: workflow_config_reports is defined
      rescue:
        - name: Set placeholder stat value
          ansible.builtin.set_fact:
            workflow_config_reports: []

    - name: Post diff to slack
      loop: "{{ workflow_config_reports }}"
      loop_control:
        loop_var: device_report
      ansible.builtin.include_tasks:
        file: tasks/post_config_report.yml
