---
- name: Unpack
  ansible.builtin.include_tasks: unpack.yml

- name: Set repo path
  ansible.builtin.set_fact:
    git_repo_path: "{{ git_url | regex_search('/(.+).git') | regex_replace('.git', '') }}"

- name: git clone
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "{{ git_repo_root }}"
    accept_hostkey: yes
    key_file: "{{ git_temp_file.path }}"
    version: "{{ git_pull_tag | default(git_branch) | default(omit) }}"

- name: Cleanup keys
  ansible.builtin.include_tasks: cleanup_keys.yml
