---
plugin: amazon.aws.aws_ec2
aws_region: us-east-2
hostnames:
  - tag:Name
keyed_groups:
  - prefix: role
    key: tags['role']
compose:
  ansible_host: public_ip_address | default(private_ip_address)
  ansible_user: ec2-user