---
- name: Update Palo Alto Firewall credential
  no_log: "{{ credential_secure_logging }}"
  ansible.controller.credential:
    name: Palo Alto Firewall (admin)
    organization: Autodotes
    credential_type: Palo Alto Networks Provider
    description: Palo Alto Firewall administrator credentials compatible with the palaltonetworks.panos collection
    inputs:
      panos_ip_address: "{{ r_eip_mgmt.public_ip }}"
      panos_username: admin
      panos_password: "{{ panos_demo_password }}"
    state: present
...