---
- name: Update Palo Alto Bastion credential
  no_log: "{{ credential_secure_logging }}"
  ansible.controller.credential:
    name: Palo Alto Bastion
    organization: Autodotes
    credential_type: SSH Proxy
    description: Palo Alto Bastion credential for supporting SSH proxy implementation
    inputs:
      ssh_proxy_username: ec2-user
      ssh_proxy_host: "{{ r_bastion_eip_public.public_ip }}"
      ssh_proxy_key: "$encrypted$"
    state: present
...