- name: Gather facts
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Gather nxos facts
      when: ansible_network_os == 'nxos'
      cisco.nxos.nxos_facts:
        gather_subset: all

    - name: Gather ios facts
      when: ansible_network_os == 'cisco.ios.ios'
      cisco.ios.ios_facts:

    - name: Create output directory
      ansible.builtin.file:
        path: "{{ playbook_dir }}/facts"
        state: directory

    - name: Write facts to file
      ansible.builtin.copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: "{{ playbook_dir }}/facts/{{ inventory_hostname }}.json"
