---
ansible_user: ec2-user

# mimicking (partially) the SSH Proxy Credential Type injector configuration
ssh_proxy_username: ec2-user
ssh_proxy_host: "{{ hostvars[groups['role_bastion'][0]]['public_ip_address'] }}"

# same group vars set in my AAP Inventory
# referencing variables from SSH Proxy Credential Type injector configuration
ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PROXY_KEY') }}"
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 
  -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 
  -i {{ lookup('env', 'SSH_PROXY_KEY') }} -W %h:%p -q {{ ssh_proxy_username }}@{{ ssh_proxy_host }}"